# ==========================================
# GENERAL
# ==========================================
set -g prefix C-s
set -g mouse on
set -g default-terminal "tmux-256color"
set-option -g default-shell /bin/zsh
set-option -g allow-rename off

# ==========================================
# UNBINDS
# ==========================================
unbind r
unbind c
unbind '"'
unbind %

# ==========================================
# KEYBINDINGS
# ==========================================

# Configuration
bind r source-file ~/.tmux.conf
bind-key C-l send-keys 'C-l'

# Pane Splits
bind | split-window -h
bind - split-window -v

# Pane Navigation
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Window Management
bind-key n new-window
bind-key l next-window
bind-key h previous-window
bind -n M-r command-prompt -p "window name:" "rename-window '%1'"

# Session Management
bind -n M-R command-prompt -p "session name:" "rename-session '%1'"

# ==========================================
# THEME CONFIGURATION
# ==========================================
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text " #{window_name}"
set -g @catppuccin_window_current_text " #{window_name}"
set -g @catppuccin_window_text " #{window_name}"

# Status Bar Layout
set -g status-left-length 100
set -g status-right-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# ==========================================
# PLUGINS
# ==========================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'catppuccin/tmux'

# Tmux plugin manager
run '~/.tmux/plugins/tpm/tpm'
